### ISSUE TITLE
postinstall script prevents 2.0.3 from being installed

### ISSUE THREAD

**Issue by mgdodge** [fatso83/retry-dynamic-import#3]
Setting up a project the other day that used 2.0.2, I thought I'd check out what 2.0.3 had. Attempting to install generates the following error:

```sh
npm ERR! command failed
npm ERR! command sh -c cd demo && npm i; cd ../test-builds && npm i
npm ERR! sh: 1: cd: can't cd to demo
npm ERR! sh: 1: cd: can't cd to ../test-builds
```

Please remove the postinstall script from the version published to npm. Rolling back and locking in 2.0.2 is currently required.

**Comment by fatso83** [comment]
Somehow I did not see that this was reported. Someone contacted my by email before I noticed and so this issue was closed some weeks ago in 8220c703727c7fbcd64439a42e7a68ab7d1834dc.

Thanks for reporting!
