### ISSUE TITLE
Cannot find module '@fatso83/retry-dynamic-import/react-lazy' or its corresponding type declarations

### ISSUE THREAD

**Issue by eranaKubiya** [fatso83/retry-dynamic-import#6]
Hey, 
Using React 18 (CRA) with typescript.

**Comment by fatso83** [comment]
Hi, thanks for reporting! I am not sure how to reproduce this, could you elaborate on how I can reproduce this? I will at the minimum require package.json and the tsconfig. 

If you look at https://github.com/fatso83/retry-dynamic-import/tree/main/test-builds you will see that for every published version I check that it works with three different ways of consuming it with TypeScript.:
<img width="1098" alt="image" src="https://github.com/fatso83/retry-dynamic-import/assets/618076/ef49e71a-564a-4608-b3cb-85a10279db5c">

Does your setup look like/deviate from any of these?

Help me help you :-)

**Comment by fatso83** [comment]
Ah, I might have gotten some progress. I checked out my own project, went into the `test-builds` directory and replaced the local version of the package with the real one and it immediately failed:

```
❯ git diff package.json 
diff --git a/test-builds/package.json b/test-builds/package.json
index 8d9d2e4..ed73348 100644
--- a/test-builds/package.json
+++ b/test-builds/package.json
@@ -14,7 +14,7 @@
     "test": "run-s typecheck build && ! (grep -i react typescript-moduleresolution-*/dist/assets/*)"
   },
   "dependencies": {
-    "@fatso83/retry-dynamic-import": "file:../pkg",
+    "@fatso83/retry-dynamic-import": "latest",

❯ npx tsc --noEmit typescript-moduleresolution-default/src/main.ts
typescript-moduleresolution-default/src/main.ts:3:40 - error TS2307: Cannot find module '@fatso83/retry-dynamic-import' or its corresponding type declarations.

3 import { dynamicImportWithRetry } from '@fatso83/retry-dynamic-import'
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in typescript-moduleresolution-default/src/main.ts:3

```

This I can work with. I have obviously been fooling myself with the synthetic testing 😢

**Comment by fatso83** [comment]
OH MY LORD. Now I get why this is failing:

```
❯ get-npm-file @fatso83/retry-dynamic-import
x package/vite.config.js
x package/package.json
x package/README.md

```

The [utility get-npm-file is this](https://github.com/fatso83/dotfiles/blob/79582685caa1c8d433a740ed8df5080699b87778/utils/scripts/get-npm-file#L4), btw.

**Comment by fatso83** [comment]
OK, this is a problem with 2.0.5. Will fix:

```
retry-dynamic-import on  main [!?] is 📦 v2.0.5 via  v20.5.0 on ☁️  (eu-north-1) on ☁️   took 7s 
❯ get-npm-file @fatso83/retry-dynamic-import@2.0.5
x package/vite.config.js
x package/package.json
x package/README.md

retry-dynamic-import on  main [!?] is 📦 v2.0.5 via  v20.5.0 on ☁️  (eu-north-1) on ☁️   took 2s 
❯ get-npm-file @fatso83/retry-dynamic-import@2.0.4
x package/index.js
x package/react-lazy.js
x package/retry-adb9725b.js
x package/package.json
x package/README.md
x package/index-all.d.ts
x package/index.d.ts
x package/react-lazy.d.ts
x package/retry.d.ts

retry-dynamic-import on  main [!?] is 📦 v2.0.5 via  
```

**Comment by eranaKubiya** [comment]
Thanks! waiting for the changes :)

**Comment by fatso83** [comment]
I think this is fixed now. There were 2 issues.

1. False security in the integration tests, as Typescript ignores types from symlinked directories (https://github.com/microsoft/TypeScript/issues/56576). This is why the tests could work locally, but not when referencing the actual package published to NPM. I have made a workaround that just copies the files for these tests to avoid this.
2. Too quick turnaround when releasing 2.0.5 caused me to miss that I did not build the required files before packing the files to publish. Added several checks to avoid this.

If you now `npm i @fatso83/retry-dynamic-import@latest` you should get 2.1.1 that hopefully works for you.

Would be great if you could report back if it works!

**Comment by fatso83** [comment]
The reporter of #5 has reported this fixed their issue from October, so that's promising 🤞

**Comment by eranaKubiya** [comment]
@fatso83  Work great!!!

**Comment by eranaKubiya** [comment]
@fatso83 
Hey, thanks for your fast and good response!! 
Another question not sure if its an issue,
when i use retry-dynamic-import/**react-lazy** and try to block some URL (as in example) the 5 time retry loop does not work.
Should it work similar to this function?
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/25d977b8-f56e-4bcd-acac-f0a59f5e82c5)

and if not, how can i add a default of  implementation with 5 retries

**Comment by fatso83** [comment]
Can you post some code? Or screenshots from the Network tab in the inspector?

**Comment by eranaKubiya** [comment]
Yes,
Import 
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/fadd05fb-130a-4232-8915-d0eea66828b1)
call component
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/c5fba516-07fa-4b4b-8ac1-c7eb3fc935fe)
Block the request chunk
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/963d107d-e1ed-4897-b076-bcb963a6e3d6)
start fallback with some loading... for 10 seconds and no retry in network as occurs.
after 10-15 seconds ChunkLoadError appear.
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/1e7bad60-e32a-4d79-bff9-690e913445f7)
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/486615b2-d9fb-413e-ba29-fc7587c690d8)

**Comment by fatso83** [comment]
Hmm ... the [demo](https://fatso83.github.io/retry-dynamic-import/demo/) is using the same code, so does that work for you when blocking and unblocking the request?

https://github.com/fatso83/retry-dynamic-import#demo

And the code looks awfully similar: https://github.com/fatso83/retry-dynamic-import/blob/main/demo/src/App.tsx

**Comment by eranaKubiya** [comment]
yes. when i try "https://fatso83.github.io/retry-dynamic-import/demo/" its work as expected.

**Comment by fatso83** [comment]
Hmm .. I am suspecting that this is really WebPack getting in your way somehow. I am not sure what it does with `import(....)` calls under the hood, but I do see it uses its own `require` in the stack trace.

**Comment by fatso83** [comment]
I would set a breakpoint at the import and see what's happening. I am thinking webpack does something too clever (different from the normal `import()`) for the tooling.

**Comment by eranaKubiya** [comment]
Thanks, that what i do also but with Alon's function "LazyReact".
managed to fixed the URL problem
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/1658542f-d862-4cdd-b740-2fe64f6a42ba)
but still failed to call again 
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/0e49aad0-af40-4b0a-84be-7c5f98a68aed)
and if i change that with:
![image](https://github.com/fatso83/retry-dynamic-import/assets/117263877/6482a729-c52d-49bd-906a-b58b45455328)
its work but no cache busting

.. also after 5 times its throw error "ChunkLoadError", how can i add some error handle instead of a blank page?

**Comment by fatso83** [comment]
You just add a react error boundary around the component

**Comment by fatso83** [comment]
It would be interesting to exactly know what Webpack does and see if I can fix it to also work with Webpack. The "Vite solution" is not specific to Vite: it works exactly like that in a browser if you copy the code out and execute it in the DevTools in Firefox or Chrome. So it's more webpack being strange than the other way around.

Is there an easy way for me to recreate the issue? Like `npx create-react-app` and then try to wrap the loading of some component?

**Comment by eranaKubiya** [comment]
[my-app.zip](https://github.com/fatso83/retry-dynamic-import/files/13509506/my-app.zip)
Added template ready for you with the issue

**Comment by fatso83** [comment]
I will see what I can do, but I am guessing this is where webpack deviates from the standard, making the easy hard, with its own dynamic custom module fetching.
